name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/forum-app-back-end
            git pull origin main
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            nvm install --lts
            node -v
            npm -v
            npm install
            npm run migrate up
            pm2 restart forum-api
